const createTable = '''
CREATE TABLE(
  id INTEGER AUTOINCREMENT PRIMARY KEY NOT NULL
  , content TEXT NOT NULL 
  , status INTEGER NOT NULL
);
''';

// FUTURAMENTE PODEMOS TRAZER O NOME DO BANCO DE DADOS PRA CA...